math = true
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"


#[header]
#  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur
#
#[footer]
#  showMenu = true
#  showCopyright = true
#  showThemeAttribution = true
#  showAppearanceSwitcher = true
#  showScrollToTop = true
#
#[homepage]
#  layout = "background" # valid options: page, profile, hero, card, background, custom
#  #homepageImage = "IMAGE.jpg" # used in: hero, and card
#  showRecent = true
#  showRecentItems = 6
#  showMoreLink = true
#  showMoreLinkDest = "posts"
#  cardView = true
#  cardViewScreenWidth = false
#  layoutBackgroundBlur = true # only used when layout equals background
#
#[article]
#  showDate = true
#  showViews = false
#  showLikes = false
#  showDateOnlyInArticle = false
#  showDateUpdated = false
#  showAuthor = true
#  showAuthorBottom = true
#  showHero = true
#  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
#  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
#  showBreadcrumbs = true
#  showDraftLabel = true
#  showEdit = true
#  editURL = "https://github.com/carnivuth/carnivuth/tree/main/content"
#  editAppendPath = true
#  seriesOpened = false
#  showHeadingAnchors = true
#  showPagination = true
#  invertPagination = false
#  showReadingTime = true
#  showTableOfContents = true
#  # showRelatedContent = false
#  #Â relatedContentLimit = 3
#  showTaxonomies = false # use showTaxonomies OR showCategoryOnly, not both
#  showCategoryOnly = true # use showTaxonomies OR showCategoryOnly, not both
#  showAuthorsBadges = false
#  showWordCount = true
#  sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
#  showZenMode = true
#
#[list]
#  showHero = true
#  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
#  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
#  showBreadcrumbs = false
#  showSummary = true
#  showViews = false
#  showLikes = false
#  showTableOfContents = true
#  showCards = true
#  orderByWeight = false
#  groupByYear = true
#  cardView = true
#  cardViewScreenWidth = false
#  constrainItemsWidth = false
#
#[sitemap]
#  excludedKinds = ["taxonomy", "term"]
#
#[taxonomy]
#  showTermCount = true
#  showHero = false
#  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  showBreadcrumbs = false
#  showViews = false
#  showLikes = false
#  showTableOfContents = false
#  cardView = false
#
#[term]
#  showHero = false
#  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  showBreadcrumbs = false
#  showViews = false
#  showLikes = false
#  showTableOfContents = true
#  groupByYear = false
#  cardView = false
#  cardViewScreenWidth = false


 [author]
   name = "Matteo Longhi"
   email = "matti200042@gmail.com"
   image = "avatar.jpg"
   imageQuality = 96
   headline = "homelab addicted guy with a passion for Music and dogs"
   bio = " I'm a software engineer with a passion for Music, food, dogs, videogames and open source software, i'm currently working as a devops engineer"
   links = [
     { email = "mailto:matti200042@gmail.com" },
     { link = "https://www.carnivuth.org/" },
     { github = "https://github.com/carnivuth" },
     { instagram = "https://instagram.com/longhi.matteo" },
     { linkedin = "https://linkedin.com/in/matteo-longhi-b3a433247" },
   ]
